OnlineShoppingStore.WebUI/Models/CartIndexViewModel.cs
using OnlineShoppingStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OnlineShoppingStore.WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

OnlineShoppingStore.WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OnlineShoppingStore.WebUI.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages {
            get{
                return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage);
            }
        }
    }
}

OnlineShoppingStore.WebUI/Models/ProductsListViewModel.cs
using OnlineShoppingStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OnlineShoppingStore.WebUI.Models
{
    public class ProductsListViewModel
    {
        public IEnumerable<Product> Products { get; set; }
        public PagingInfo PagingInfo { get; set; }  //we do not need to add the namespace for PagingInfo because they are in the same folder
        public string CurrentCategory { get; set; }
    }
}

OnlineShoppingStore.WebUI/Controllers/CartController.cs
using OnlineShoppingStore.Domain.Abstract;
using OnlineShoppingStore.Domain.Entities;
using OnlineShoppingStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShoppingStore.WebUI.Controllers
{

    public class CartController : Controller
    {

        private IProductRepository repository;     //collection of products

        public CartController(IProductRepository repo)
        {
            repository = repo;
        }


        public ViewResult Index(string returnUrl)
        {
            return View(
                new CartIndexViewModel { Cart = GetCart(), ReturnUrl = returnUrl }); //this are the properties of CartIndexViewModel
        }
        
        

        public RedirectToRouteResult AddToCart(int productId, string returnUrl)  //recieving from ProductSummary View
        {
      
            Product product = repository.Products.FirstOrDefault(p => p.ProductID == productId);  //search a product from a collection(of products) via recieved productId
            //repository = IProductRespository = collection of Products where Products has ProductID property
            if (product != null)   //if product is existed(this system is just for foolproof), we have to add the product to our cart
            {
                GetCart().AddItem(product, 1);  //AddItem is a method of Cart class, add item into the new cart
                //AddItem method recieves a product object and adds a new Item in the list of ordered goods, one at a time every click, that's why it's 1
            }
            
            return RedirectToAction("Index", new {returnUrl});
        }


        public RedirectToRouteResult RemoveFromCart(int productId, string returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductID == productId);

            if (product != null)   
            {
                GetCart().RemoveLine(product);
            }
            
            return RedirectToAction("Index", new {returnUrl});
        }


        private Cart GetCart()
        {
            Cart cart = (Cart)Session["Cart"];   // cart = new Cart(); if it is not null
            if (cart == null)
            {
                cart = new Cart();         //make a new cart object
                Session["Cart"] = cart;    //store the new cart into session, a Session could store any type of object
                //Session variables are stored on the web server by default, and are kept for a lifetime of a session
                //available across all pages, but only for a single session
                //like single-user global data
            }
            return cart;
        }
        
    }
}

OnlineShoppingStore.WebUI/Controllers/NavController.cs
using OnlineShoppingStore.Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShoppingStore.WebUI.Controllers
{
    public class NavController : Controller
    {   //if there is a NavController, then there is a Nav View folder, this one contains one cshtml partial page called Menu.cshtml
        //Menu holds the Home button, and buttons of different categories generated by the Menu method residing here

        private IProductRepository repository;    //IProductRepository has a single property, contains collection of Products

        public NavController(IProductRepository repo)         //this is called dependency injection
        {
            repository = repo;  //repository shall have Products and the properties of Product
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;          

            IEnumerable<string> categories = repository.Products    //query all unique Category value in IProductRepository and make it a categories collection
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(categories);  //category names
        }
    }
}

OnlineShoppingStore.WebUI/Controllers/ProductController.cs
using OnlineShoppingStore.Domain.Abstract;
using OnlineShoppingStore.WebUI.Models;
using System.Linq;
using System.Web.Mvc;

namespace OnlineShoppingStore.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductRepository repository;
        public int PageSize = 4;

        public ProductController(IProductRepository repo)
        {
            repository = repo;
        }

        public ViewResult List(string category, int page = 1) {
            //we are sending a category parameter so we could not just view all records but we could also filter out our desired result in the url
            ProductsListViewModel model = new ProductsListViewModel //contains a list of Products and an instance of PagingInfo
            {
                Products = repository.Products    // the query for changing pages
                    .Where(p=>category == null || p.Category == category)  //could accept category being not sent or sent by the user
                    .OrderBy(p=>p.ProductID)
                    .Skip((page-1)*PageSize)      //the formula for making pages
                    .Take(PageSize),
                PagingInfo = new PagingInfo      //set the initial property values of PagingInfo
                {
                    CurrentPage = page,    //a page value that gets past to the url, initial value is 1 if nothing is passed
                    ItemsPerPage = PageSize, //value of PageSize is in this controller, default value is 4
                    TotalItems = category == null ?
                                 repository.Products.Count() : //if there are no category being sent by the user, just the total count
                                 repository.Products.Where(p=>p.Category==category).Count()  
                    //There is a missing property here that is TotalPages, in which it uses TotalItems and ItemsPerPage to determine it's value. It has no setter
                    //TotalPages is automatically set via TotalItems/ItemsPerPage                    
                },
                CurrentCategory = category   //value of category is inside route.config, this line is gonna use for the hyperlinks below the site
            };

            return View(model);
        }
    }
}

OnlineShoppingStore.WebUI/Views/Cart/Index.cshtml
@model OnlineShoppingStore.WebUI.Models.CartIndexViewModel

@{
    ViewBag.Title = "Sports Store: Your Cart";
}
<h2>Your cart</h2>
<table class="table">
    <thead>
        <tr>
            <th>Quantity</th>
            <th>Item</th>
            <th class="text-right">Price</th>
            <th class="text-right">Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)                           
        {
            <tr>
                <td class ="text-center"> @line.Quantity</td>
                <td class="text-left">@line.Product.Name</td>
                <td class="text-right">@line.Product.Price.ToString()</td>
                <td class="text-right">
                    @((line.Quantity * line.Product.Price))
                </td>
             </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total:</td>
            <td class="text-right">@Model.Cart.ComputeTotalValue().ToString("c")</td>
        </tr>
    </tfoot>
</table>
<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">  @*returns to /Product/List*@
        Continue Shopping
    </a>
</div>

OnlineShoppingStore.WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@*This is the sidebar*@

@Html.ActionLink("Home", "List", "Product", null, new {@class= "btn btn-block btn-default btn-lg" })


@*list of categories*@
@foreach(var link in Model){
    
    @Html.RouteLink(link, 
    new{
    controller = "Product",
    action ="List",
    category = link,
    page = 1
    },
    new {@class = "btn btn-block btn-default btn-lg" + (link == ViewBag.SelectedCategory? " btn-primary":"")}
    )
}

OnlineShoppingStore.WebUI/Views/Product/List.cshtml
@model OnlineShoppingStore.WebUI.Models.ProductsListViewModel

@{
    ViewBag.Title = "Products";
}

@*ProductSummary holds the template for each product in the list*@


@foreach (var p in Model.Products)
{
@Html.Partial("ProductSummary", p)     @*DRY*@
}

@*This are the pages. PageLinks is an extension Method, it is located at /HtmlHelpers/PagingHelpers*@
<div class="btn-group pull-right">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x, category=Model.CurrentCategory }))
</div>
@*List is an action method, page and category is a variable in the route.config, CurrentCategory is a property of ProductListViewModel*@

OnlineShoppingStore.WebUI/Views/Shared/ProductSummary.cshtml
@model OnlineShoppingStore.Domain.Entities.Product

@*this is the page for each individiual product in the list*@
@*here also resides the add to cart button*@
@*this is a partial view being used by /Product/List to display a list of products*@
@*Products class was obtained via ProductListViewModel model, in which it contains IEnumerable<Product> Products*@

<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("c")</span>
    </h3>
    @using (Html.BeginForm("AddToCart", "Cart"))
    {                                               @*sends ProductID and a returnUrl value to AddtoCart method from CartController*@
        <div class="pull-right">
            @Html.HiddenFor(x => x.ProductID)                                      @*Product Model, it has direct access to it via the model passed to this view*@
            @*HiddenFor is an Html.Hidden variant*@
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)                  @*<input type="returnUrl" value=Request.Url.PathAndQuery />, returnUrl property came from CartIndexViewModel*@
            @*we are not using HiddenFor because we don't have a direct access to returnUrl Property*@
            <input type="submit" class="btn btn-success" value="Add to Cart" />
        </div>
    }
    <span class="lead">@Model.Description</span>
</div>

OnlineShoppingStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">Online ShoppingStore</a>
    </div>
    <div class="row panel">
        <div id="categoris" class="col-lg-3">
            @Html.Action("Menu", "Nav")
        </div>
        <div class="col-lg-7">
            @RenderBody()
        </div>
    </div>
</body>
</html>